### ISSUE TITLE
User, Volunteer Rosa Harmon, not receiving text messages

### ISSUE THREAD

**Issue by DarcyBlank** [OfficeMomsandDads/scheduler#194]
Efforts to date: We deleted original profile and created new one. Still doesn't receive text messages for needs at Vancouver office. All her info looks correct to me. (Her husband does receive the messages, which is how we know she is not.)

**Comment by kyleboe** [comment]
Looks like we received an [error `30005`](https://www.twilio.com/docs/api/errors/30005) recently.

My best guess is that it is caused by one of the two things below:

- The device cannot receive SMS (for example, the phone number belongs to a landline)
- There is an issue with the mobile carrier

To eliminate potential issues with the carrier, she will want to make sure her number in the correct [E.164](https://www.twilio.com/docs/glossary/what-e164) format:

```
[+] [country code] [subscriber number including area code]
```

**Comment by sarahwicks** [comment]
Update 5/22

- Number is able to receive SMS
- Husband is on same carrier, he is receiving text messages without a problem
- User updated phone number to E.164 format
-Can't test until we resolve #197 (text messages aren't going out to any users right now)

**Comment by DarcyBlank** [comment]
#197 has been resolved. User Rosa Harmon still having this issue. Also received notification on 5/29/19 that volunteer Jean Loven,  jeanloven@aol.com, in Monroe was experiencing same issue.
