### ISSUE TITLE
Edit profile / password

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#367]
While testing #365 I noticed that we ask the user to enter a password when updating their profile. When they do, I got an error saying that 'current password' is required but there is no field for it in the form. However, the profile fields I had changed were updated. :man_shrugging: 

Anyways, I think we should have a separate password change action that requires the current password to be entered. The general profile form should not include anything related to the password at all.

**Comment by joelmichael** [comment]
This problem is actually caused by the old seed data. I fixed it in https://github.com/OfficeMomsandDads/scheduler/pull/358. If you re-plant your seed data, your default admin account should be set up properly to avoid this issue.

**Comment by benjaminwood** [comment]
Which problem specifically? Doesn't the profile edit form still include a password field that is required?

**Comment by joelmichael** [comment]
Yes, the current password is required, and we could see about changing that. The problem solved by that PR is that the admin user didn't have it marked that they had accepted the invitation, and that's why the current password field wasn't showing up, so it was impossible to edit the profile of the default account.

**Comment by benjaminwood** [comment]
Oh, I see! Great, thanks for fixin' that part (already!)
